name: Lint

on:
  push:
    branches:
      - main
      - develop
      - duck
  pull_request:
    branches:
      - main
      - develop
      - duck

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          package-manager: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
