name: CI
on:
  push:
    branches:
      - duck
  pull_request:
    branches:
      - duck

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # Optional: specify a pnpm version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Specify the Node.js version
          cache: 'pnpm' # Enables caching for pnpm dependencies

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Installs dependencies

      - name: Run lint
        run: pnpm lint # Executes the 'lint' script from package.json
